
#**Laboratorio (6%)**

**Instrucciones:** El presente trabajo consta de seis (6) problemas cada uno con un valor asignado. El profesor del curso es el encargado de calificar el trabajo, y para ello tendrá en cuenta el  procedimiento realizado (que debe mostrar el estudiante) y las respectivas respuestas a los ejercicios. Por favor, **comentar de forma organizada y coherente** los pasos realizados.


 El laboratorio **debe ser realizado en grupos, con el número máximo integrantes definido por el profesor**. Se debe entregar un solo documento por grupo, y dentro del mismo **debe aparecer de forma clara el nombre completo de todos los integrantes**.  Ver espacio a continuación.


**Formato de entrega:** Para la entrega de este trabajo, descargue el archivo en **formato PDF** (esto lo consigue con la combinación de teclas **ctrl + p** y guardando el archivo en el formato requerido) y enviarlo a través de Interactiva en el buzón designado para ello.

**NOTA:** Revisar el documento antes de enviarlo. Asegúrese de que el documento sea legible y tenga todos los procedimientos con las respuestas impresas de los cálculos realizados.

In [1]:
########---------------Nombre completo de los integrantes del grupo de trabajo-------------------##########

# Integrante 1: Thomas Serna Saldarriaga

# Integrante 2: Juan Esteban Palacio Betancur

# Integrante 3: Stephanie Jaramillo Alzate

# Integrante 4: Juan Fernando Gomez Rivas


### **Ejercicio #1: (0.8)**
Dados los siguientes vectores

\begin{equation*}
 \vec{u} = (10, 33, 7),
 \hspace{0.5cm}
 \vec{v} = (0, -79, -12),
\hspace{0.5cm}
 \vec{w} = (25, 56, 28),
 \hspace{0.5cm}
 \vec{z} = (-10, 0, 58),
\end{equation*}

realizar las operaciones indicadas:

a). **(0.2)** $ (\vec{u} + \vec{z}- \vec{v}) \cdot (\vec{z}-3\vec{w} + \vec{v}).$

b). **(0.2)** $\| \vec{z}- \vec{w}\|- \|\vec{w} \times \vec{u}\|.$

c). **(0.2)** $\|\vec{u}\|(\vec{v} + \vec{z}) + \| 2\vec{z}- 3\vec{w}\|\vec{z}.$

d). **(0.2)** Hallar dos vectores $\vec{p}$ y $\vec{h}$ tales que $\vec{v} = \vec{p} + \vec{h}$ con $\vec{p}$ paralelo a $\vec{u}$ y $\vec{h}$ ortogonal a $\vec{u}$.

In [2]:
# Solución Ejercicio 1.

# Importar la bibliotecas numpy con el alias np
import numpy as np

# Definir los vectores u,v,w,z
u = np.array([10, 33, 7])
v = np.array([0, -79, -12])
w = np.array([25, 56, 28])
z = np.array([-10, 0, 58])

# (a):

# Primero, calculamos el primer vector de la operación: (u + z - v)
vec1_a = u + z - v
# Segundo, calculamos el segundo vector: (z - 3*w + v)
vec2_a = z - (3 * w) + v

# Finalmente, usamos la función 'np.dot' para calcular el producto punto (producto escalar)
# entre los dos vectores que acabamos de encontrar.
resultado_a = np.dot(vec1_a, vec2_a)

print(f"Resultado 1.A: {resultado_a}\n")

# (b):

# Calculamos el vector resultante de la resta (z - w).
vec1_b = z - w
# Usamos 'np.linalg.norm' para calcular la norma (magnitud o longitud) de este vector.
norma1_b = np.linalg.norm(vec1_b)

# Usamos 'np.cross' para calcular el producto cruz (producto vectorial) entre w y u (w x u).
vec2_b = np.cross(w, u)
# Calculamos la norma del vector resultante del producto cruz.
norma2_b = np.linalg.norm(vec2_b)

# Realizamos la resta de las dos normas.
resultado_b = norma1_b - norma2_b

print(f"Resultado 1.B: {resultado_b:.4f}\n")

# (c):
# Calculamos la norma (magnitud) del vector u.
norma_u = np.linalg.norm(u)
# Realizamos la multiplicación escalar: ||u|| * (v + z).
norma_u_por_v_mas_z = norma_u * (v + z)

# Calculamos el vector (2*z - 3*w) y luego su norma.
# Esta norma la multiplicamos escalarmente por el vector z.
norma_2z_3w_por_z = np.linalg.norm((2 * z) - (3 * w)) * z

# Sumamos los dos vectores resultantes.
resultado_c = norma_u_por_v_mas_z + norma_2z_3w_por_z

print(f"Resultado 1.C: {resultado_c}\n")

# (d):
# Esta parte pide la proyección de v sobre u (vector p) y su componente ortogonal (vector h).
# p = proy_u(v) = ((v ⋅ u) / ||u||^2) * u

# Calculamos el producto punto (v ⋅ u).
v_dot_u = np.dot(v, u)
# Calculamos el cuadrado de la norma de u (||u||^2).
norma_u_sq = np.linalg.norm(u)**2

# Calculamos el vector p (proyección) usando la fórmula.
p = (v_dot_u / norma_u_sq) * u
# Calculamos el vector h (componente ortogonal) usando la resta h = v - p.
h = v - p

print("Resultado 1.D:")
print(f"Vector p (paralelo a u): {p}")
print(f"Vector h (ortogonal a u): {h}")

print("Verificación:")
print(f"u ⋅ h: {np.abs(round(np.dot(u,h), 4))}")
print(f"p + h: {p+h}")


Resultado 1.A: -30590

Resultado 1.B: -531.0184

Resultado 1.C: [-2308.2008814  -2779.63270955 12965.34242207]

Resultado 1.D:
Vector p (paralelo a u): [-21.73667205 -71.73101777 -15.21567044]
Vector h (ortogonal a u): [21.73667205 -7.26898223  3.21567044]
Verificación:
u ⋅ h: 0.0
p + h: [  0. -79. -12.]


### **Ejercicio #2. (1.2)**
Andrea ha decidido enviarle un mensaje codificado a Camilo a través del **método Hill**. El mensaje codificado es:

-8, 4, -9, -1, 19, 13, 11, 23, 6, 13, 5, 27, 140, 68, 141, 75, 85, 155, 83, -1, 84, 125, 97, 69, 124, 46, 139, 51, 117,  155, 83, -1, 110,  113, 115, 87, -108,  -40,  -92,  -18,  -96, -136,  -54, 34, -76, -94, -92, -58, 102,  58,  103,   43,   45,   99,   57, -3, 44, 69, 63, 37.

Para el proceso de codificacion, Andrea tuvo presente la siguiente información:

1. Llave de codificación: 0, 0, 1, -1, 0, 0, 4, -1, 1, 2, -2, 4, 1, 1, 2, 2, -4, 0, 0, -2, 0, 2, -1, 1, 2.
2. Dimensión de la matriz de codificación $5 \times 5$.

a). **(0.4)** Cree e imprima la matriz de codificación $A$, y la matriz codificada $C$.

b). **(0.4)** Cree e imprima la matriz plana $B$ (matriz que contiene el mensaje que se desea codificar).

c). **(0.4)** ¿Cuál es el mensaje que le envío Andrea a Camilo?


**NOTA:** Remitirse a la **Guía # 3** en la cual se explica el Método Hill.

In [3]:
# Solución ejercicio 2.

# Importar la biblioteca numpy con el alias np.
import numpy as np

# Definir e imprimir las matrices A y C

# Matriz A (Matriz de codificación 5x5)
# Creamos la matriz A usando los números de la "llave de codificación".
A = np.array([
    [ 0,  0,  1, -1,  0],
    [ 0,  4, -1,  1,  2],
    [-2,  4,  1,  1,  2],
    [ 2, -4,  0,  0, -2],
    [ 0,  2, -1,  1,  2],
], dtype=int)

# Matriz C (Matriz codificada)
# Creamos la matriz C con el mensaje codificado.
# Dado que A es 5x5, agrupamos el mensaje en 5 filas.
# El mensaje tiene 60 números, por lo que C será 5x12.
C = np.array([
    [-8,   4,  -9,  -1,  19,  13,  11,  23,   6,  13,   5,  27],
    [140, 68, 141,  75,  85, 155,  83,  -1,  84, 125,  97,  69],
    [124, 46, 139,  51, 117, 155,  83,  -1, 110, 113, 115,  87],
    [-108,-40, -92, -18, -96,-136, -54,  34, -76, -94, -92, -58],
    [102, 58, 103,  43,  45,  99,  57,  -3,  44,  69,  63,  37],
], dtype=int)

# (a):
print("Matriz A (5x5):")
print(A)

print("\nMatriz C (5x12): ")
print(C)

Matriz A (5x5):
[[ 0  0  1 -1  0]
 [ 0  4 -1  1  2]
 [-2  4  1  1  2]
 [ 2 -4  0  0 -2]
 [ 0  2 -1  1  2]]

Matriz C (5x12): 
[[  -8    4   -9   -1   19   13   11   23    6   13    5   27]
 [ 140   68  141   75   85  155   83   -1   84  125   97   69]
 [ 124   46  139   51  117  155   83   -1  110  113  115   87]
 [-108  -40  -92  -18  -96 -136  -54   34  -76  -94  -92  -58]
 [ 102   58  103   43   45   99   57   -3   44   69   63   37]]


In [4]:
# Definir e imprimir la matriz B

# El método Hill se basa en la ecuación matricial C = A * B,
# donde C es el mensaje codificado, A es la llave y B es el mensaje original.
# Para encontrar B, debemos despejar: B = A⁻¹ * C (A inversa por C).

# Usamos 'np.linalg.inv(A)' para calcular la matriz inversa de A (A⁻¹).
A_inv = np.linalg.inv(A)
# Usamos el operador '@' para realizar la multiplicación de matrices entre A⁻¹ y C.
B = A_inv @ C

# (b):
print("Matriz B (5x12):")
print(B)

Matriz B (5x12):
[[12. 16. 20. 28.  4. 16. 20. 28.  7. 22.  5. 19.]
 [19.  5. 19. 16. 20. 28. 13.  1. 20. 28. 17. 16.]
 [ 4.  5. 19. 16. 20. 16. 20. 28. 20. 16. 14. 28.]
 [12.  1. 28. 17.  1.  3.  9.  5. 14.  3.  9.  1.]
 [28. 26. 28.  5. 12. 28. 21.  9.  5. 13. 17. 16.]]


In [5]:
# Mensaje que envío Andrea a Camilo

# Función para pasar arreglo a texto, usando el metodo hill
def arreglo_a_texto(matriz):

    # 'mapa_letras' es un "diccionario" que asigna cada número a su letra correspondiente.
    mapa_letras = {
        1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E', 6: 'F', 7: 'G', 8: 'H', 9: 'I',
        10: 'J', 11: 'K', 12: 'L', 13: 'M', 14: 'N', 15: 'Ñ', 16: 'O', 17: 'P',
        18: 'Q', 19: 'R', 20: 'S', 21: 'T', 22: 'U', 23: 'V', 24: 'W', 25: 'X',
        26: 'Y', 27: 'Z', 28: ' '
    }

    mensaje = ""

    for i in range(0, matriz.shape[0]):
        for j in range(0, matriz.shape[1]):
            # Para cada número en la matriz B (redondeado), buscamos su letra
            # correspondiente en 'mapa_letras' y la añadimos al 'mensaje'.
            mensaje += str(mapa_letras[B[i][j]])

    return mensaje

#(c):
print(arreglo_a_texto(B))

LOS DOS GUERREROS MAS PODEROSOS SON LA PACIENCIA Y EL TIEMPO


### **Ejercicio #3: (0.6)**
Considere la matriz

\begin{equation*}
 A =
\begin{pmatrix}
 -k & k-1 & k+1 & k\\
4 & 3 & 3 & 4\\
-k+1 & k+1 & k+4 & -2 \\
-2 & 3 & 4 & 6
\end{pmatrix}.
\end{equation*} \


a). **(0.3)**  Halle los valores de $k$ para los cuales la matriz $A$ tiene inversa.

b). **(0.3)**  Halle los valores de $k$ para los cuales $\det(A) = 2+3k$.


In [6]:
# Solución Ejercicio 3.

import sympy as sp

# Definimos 'k' como un símbolo algebraico.
k = sp.symbols('k')

A = sp.Matrix([
    [-k,   k-1, k+1,  k],
    [ 4,      3,   3, 4],
    [1-k,  k+1, k+4, -2],
    [-2,     3,   4, 6]
])

# Usamos 'A.det()' para calcular el determinante de A.
# El resultado será una expresión algebraica en términos de 'k'.
# 'sp.simplify' simplifica esa expresión.
det_A = sp.simplify(A.det())

# Un teorema fundamental del álgebra lineal dice que una matriz A
# tiene inversa si y sólo si su determinante es diferente de cero (det(A) ≠ 0).
# Por lo tanto, primero encontramos los valores de 'k' que hacen que det(A) = 0.
# 'sp.solve(det_A, k)' resuelve la ecuación det_A = 0 para la variable k.
k_sin_inversa = sp.solve(det_A, k)

# (a):
print(f"El determinante es: {det_A}")
print(f"La matriz A tiene inversa para todos los valores diferentes de:\n{k_sin_inversa[0]} y {k_sin_inversa[1]}")

El determinante es: -7*k**2 - 11*k + 232
La matriz A tiene inversa para todos los valores diferentes de:
-11/14 + sqrt(6617)/14 y -sqrt(6617)/14 - 11/14


In [7]:
# Solución Ejercicio 3.

# Usamos el determinante simbólico 'det_A' que calculamos en la celda anterior.
# Creamos una ecuación simbólica 'ecuacion_b' que representa det(A) = 2 + 3k.
# 'sp.Eq(expresion_izquierda, expresion_derecha)' crea la ecuación.
ecuacion_b = sp.Eq(det_A, 2 + 3*k)

# Usamos 'sp.solve' para resolver esta nueva ecuación para 'k'.
solucion_k_b = sp.solve(ecuacion_b, k)

# (b):
print(f"Los valores de k para los que det(A) = 2 + 3k son:\n{solucion_k_b[0]} y {solucion_k_b[1]}")

Los valores de k para los que det(A) = 2 + 3k son:
-1 + sqrt(1659)/7 y -sqrt(1659)/7 - 1



### **Ejercicio #4: (0.7)**
Sean $A(x_1,y_1), \ B(x_2,y_2)$ y $C(x_3,y_3)$ tres puntos en el plano $xy$. El área del triángulo formado por dichos puntos $A,B,C$ es dada por la expresión  

\begin{equation*}
 \mbox{Área} = \frac{1}{2} \left | \det
\begin{pmatrix}
x_1 & y_1 & 1\\
x_2 & y_2 & 1 \\
x_3 & y_3 & 1
\end{pmatrix} \right|,
\end{equation*}

donde el símbolo $|.|$ denota el valor absoluto.

a). **(0.3)** Sean $A(-10,6), \ B(-4,6)$ y $C(-8,22)$. Halle el área del triángulo formado por los puntos $A, \ B, \ C$.  

b). **(0.4)**  ¿Para qué valores de $k$ el **cuadrado del área del triángulo** formado por los puntos $A(0,k), \ B(-3,k)$ y $C(k,2)$ es igual a $36 \ \mbox{cm}^4$?

In [8]:
# Solución Ejercicio 4. (No olvide imprimir las respuestas de sus cálculos)

import numpy as np

# Definimos las coordenadas de los puntos A, B y C.
A_a = [-10, 6]
B_a = [-4, 6]
C_a = [-8, 22]

# Construimos la matriz 3x3 de la fórmula del área,
# usando las coordenadas (x, y) de cada punto y una tercera columna de 1's.
matriz_a = np.array([
    [A_a[0], A_a[1], 1],
    [B_a[0], B_a[1], 1],
    [C_a[0], C_a[1], 1]
])

# Calculamos el determinante de esta matriz.
determinante_a = np.linalg.det(matriz_a)

# Aplicamos la fórmula del área: Area = (1/2) * |determinante|
# 'np.abs' calcula el valor absoluto.
area = 0.5 * np.abs(determinante_a)

# (a):
print(f"El determinante es: {round(determinante_a, 2)}")
print(f"El área del triángulo con vértices A(-10, 6), B(-4, 6) y C(-8, 22) es: {round(area, 2)}")

El determinante es: 96.0
El área del triángulo con vértices A(-10, 6), B(-4, 6) y C(-8, 22) es: 48.0


In [9]:
# Solución Ejercicio 4.

k = sp.Symbol('k')

# Definimos las coordenadas de los puntos A, B y C en términos de 'k'.
A_b = [0, k]
B_b = [-3, k]
C_b = [k, 2]

# Construimos la matriz simbólica 3x3 con 'sympy'.
matriz_b = sp.Matrix([
    [A_b[0], A_b[1], 1],
    [B_b[0], B_b[1], 1],
    [C_b[0], C_b[1], 1]
])

# Calculamos el determinante simbólico, que será una expresión en 'k'.
determinante_b = matriz_b.det()

# Definimos simbólicamente el área (sin el valor absoluto por ahora).
area = (determinante_b/2)

# Creamos la ecuación (Area)² = 36.
# Al elevar al cuadrado, el valor absoluto de la fórmula original se maneja automáticamente.
# (Area)² = ( (1/2) * |det| )² = (1/4) * (det)²
ecuacion = sp.Eq(area**2, 36)

# Resolvemos la ecuación para 'k'.
valores_k = sp.solve(ecuacion, k)

# (b):
print(f"El determinante es: {determinante_b}")
print(f"Los valores de k para los que el cuadrado del área es 36 cm4 son:\n{valores_k[0]} y {valores_k[1]}")

El determinante es: 3*k - 6
Los valores de k para los que el cuadrado del área es 36 cm4 son:
-2 y 6


### **Ejercicio #5: (0.7)**
Considere el conjunto de vectores de $\mathbb{R}^6$:

$$ S = \{ (1,0,1,0,0,0), (0,1,0,1,0,1), (-1,1,0,0,1,1), (0,0,-1,-1,1,-1),(-1,0,-2,0,1,0), (0,0,0,1,-1,1)\}.     $$

(a). **(0.3)** Muestre que dicho conjunto $S$ es una base para $\mathbb{R}^6$.

(b). **(0.4)** Determinar las coordenadas del vector $(5, -2, 3,-1,7,-4)$ en dicha base.

In [10]:
# Solución Ejercicio 5.
import sympy as sp

# Definimos los 6 vectores de R^6 como Matrices columna de 'sympy'.
v1 = sp.Matrix([1, 0, 1, 0, 0, 0])
v2 = sp.Matrix([0, 1, 0, 1, 0, 1])
v3 = sp.Matrix([-1, 1, 0, 0, 1, 1])
v4 = sp.Matrix([0, 0, -1, -1, 1, -1])
v5 = sp.Matrix([-1, 0, -2, 0, 1, 0])
v6 = sp.Matrix([0, 0, 0, 1, -1, 1])

# Creamos una matriz S de 6x6, donde las columnas son los vectores v1 a v6.
# 'sp.Matrix.hstack' apila los vectores horizontalmente (como columnas).
S = sp.Matrix.hstack(v1, v2, v3, v4, v5, v6)

# Calculamos el determinante de esta matriz S.
det_S = sp.factor(S.det())
# También calculamos el rango de la matriz S.
rango_S = S.rank()

# (a)
print(f"El determinante de la matriz (det(S) = {det_S}) es diferente de 0, su rango es {rango_S} y son 6 vectores linealmente independientes, por lo tanto, S es una base de R6")

El determinante de la matriz (det(S) = -1) es diferente de 0, su rango es 6 y son 6 vectores linealmente independientes, por lo tanto, S es una base de R6


In [11]:
# Solución Ejercicio 5.

# Definimos el vector v = (5, -2, 3, -1, 7, -4)
v = sp.Matrix([5, -2, 3, -1, 7, -4])

# El metodo .LUsolve() resuelve el sistema S*c = v
coordenadas = S.LUsolve(v)

# (b):
print(f"El vector v es: {v}")
print(f"Las coordenadas del vector v en la base S son: {coordenadas}")

El vector v es: Matrix([[5], [-2], [3], [-1], [7], [-4]])
Las coordenadas del vector v en la base S son: Matrix([[10], [1], [-3], [-9], [8], [-11]])


### **Ejercicio #6: (1.0)**
Considere el conjunto

$$ V= \{ \textbf{u} = (u_1,u_2):  u_{1},u_{2} \in \mathbb{R} \}.$$

Para  $\textbf{u} = (u_1,u_2)$, $\textbf{w} = (w_1,w_2)$ en  $V$ y $\alpha \in \mathbb{R}$ se definen  las operaciones:

$$\textbf{u} \oplus \textbf{w} := (u_1 + w_1 + 2,u_2 + w_2 + 2),$$

$$ \alpha \odot \textbf{u} := (\alpha + \alpha u_1 -1,\alpha + \alpha u_2 -1).   $$

a). **(0.2)** Muestre que el elemento neutro aditivo es $\textbf{0} = (-2,-2)$,  verificando la igualdad $\textbf{0} \oplus (-10,5) = (-10,5).$

b). **(0.3)** Halle $  3 \odot [(2,-5)\oplus (-7,4)]. $

c).**(0.3)** Halle $  3 \odot (2,-5) \oplus 3 \odot (-7,4). $

d). **(0.2)** ¿Es $V$, con esas operaciones definidas, un espacio vectorial?


In [12]:
#########---------- Ejecutar esta parte antes de dar respuestas a las preguntas-----------#########

# NOTA: Las operaciones suma y producto aqui definidas pueden ser calculadas  mediante las siguientes funciones:

SUMA = lambda u,w:  np.array([[u[0,0] + w[0,0] + 2, u[0,1] + w[0,1] + 2]])

# La función SUMA recibe como entradas los elementos u,w y devuelve como resultado la suma según la definición.

PRODUCTO = lambda alpha,u:  np.array([[alpha + alpha*u[0,0] - 1, alpha + alpha*u[0,1] - 1]])

# La función PRODUCTO recibe como entradas un número real alpha y un elemento u de V, y da como resultado el producto por un escalar según la definición.

# Ejemplo: Hallemos la suma de u = (2,7) con w = (0,4).

u = np.array([[2, 7]])

w = np.array([[0, 4]])

Sol = SUMA(u,w)

print('Sol =', Sol)


Sol = [[ 4 13]]


In [13]:
# Solución Ejercicio 6.

# Definimos el vector neutro propuesto 0 = (-2, -2).
cero = np.array([[-2, -2]])
# Definimos el vector v = (-10, 5) para la prueba.
v = np.array([[-10, 5]])
# Calculamos 0 ⊕ v usando la función 'SUMA' definida.
resultado_a = SUMA(cero, v)

# (a):
print(f"El vector neutro es: 0 = {cero[0]}")
print(f"El vector a sumar es: v = {v[0]}")
print(f"Resultado de 0 ⊕ v: {resultado_a[0]}")

El vector neutro es: 0 = [-2 -2]
El vector a sumar es: v = [-10   5]
Resultado de 0 ⊕ v: [-10   5]


In [14]:
# Solución Ejercicio 6.

# Definimos los vectores u = (2, -5) y w = (-7, 4).
u_b = np.array([[2, -5]])
w_b = np.array([[-7, 4]])
# Definimos el escalar alpha = 3.
alpha_b = 3

# Esto calcula α ⊙ (u ⊕ w).
resultado_b = PRODUCTO(3, SUMA(u_b, w_b))

# (b):
print(f"Solución: {resultado_b[0]}")

Solución: [-7  5]


In [15]:
# Solución Ejercicio 6.

# Esta operación corresponde a (α ⊙ u) ⊕ (α ⊙ w).
resultado_c = SUMA(PRODUCTO(3, u_b), PRODUCTO(3, w_b))

# (c):
print(f"Solución: {resultado_c[0]}")

Solución: [-9  3]


In [16]:
# Solución Ejercicio 6.

alpha = 3.0
# p1 es el lado izquierdo (resultado de la parte b)
p1 = PRODUCTO(alpha, SUMA(u_b, w_b)) # α ⊙ (u ⊕ w)
# p2 es el lado derecho (resultado de la parte c)
p2 = SUMA(PRODUCTO(alpha, u_b), PRODUCTO(alpha, w_b)) # (α ⊙ u) ⊕ (α ⊙ w)

# Comparamos si los dos vectores resultantes (p1 y p2) son iguales.
sonIguales = np.allclose(p1, p2)

# (d):

# Imprimimos ambos resultados para la verificación.
print("α ⊙ (u ⊕ w) =", p1[0])
print("(α ⊙ u) ⊕ (α ⊙ w) =", p2[0], "\n")

# Si no son iguales, el axioma de distributividad falla.
if sonIguales:
    print("Se cumple la distributividad, por lo tanto, V es un espacio vectorial")
else:
    print("No se cumple la distributividad, por lo tanto, V no es un espacio vectorial")

α ⊙ (u ⊕ w) = [-7.  5.]
(α ⊙ u) ⊕ (α ⊙ w) = [-9.  3.] 

No se cumple la distributividad, por lo tanto, V no es un espacio vectorial
